# Generated by Django 5.2.4 on 2025-07-21 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام سایز')),
            ],
            options={
                'verbose_name': 'گزینه سایز',
                'verbose_name_plural': 'گزینه\u200cهای سایز',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام غذا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='rest.category', verbose_name='دسته\u200cبندی')),
                ('available_sizes', models.ManyToManyField(to='rest.sizeoption', verbose_name='سایزهای موجود')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام ماده اولیه')),
                ('unit_of_measurement', models.CharField(choices=[('gram', 'گرم'), ('kg', 'کیلوگرم'), ('milliliter', 'میلی لیتر'), ('liter', 'لیتر'), ('piece', 'عدد')], max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی فعلی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_materials', to='rest.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'ماده اولیه',
                'verbose_name_plural': 'مواد اولیه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار لازم')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='توضیحات خاص')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.food', verbose_name='غذا')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.rawmaterial', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'ماده اولیه غذا',
                'verbose_name_plural': 'مواد اولیه غذا',
                'ordering': ['raw_material__name'],
                'unique_together': {('food', 'raw_material')},
            },
        ),
    ]
