# Generated by Django 5.2.4 on 2025-07-26 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Food2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام غذا')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته بندی')),
                ('preparation_time_minutes', models.IntegerField(blank=True, null=True, verbose_name='زمان آماده\u200cسازی (دقیقه)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
            },
        ),
        migrations.CreateModel(
            name='loginToAddFoodPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='loginTokitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام ماده')),
                ('unit', models.CharField(max_length=50, verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'ماده اولیه',
                'verbose_name_plural': 'مواد اولیه',
            },
        ),
        migrations.CreateModel(
            name='rwmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام ماده')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار')),
                ('unit', models.CharField(max_length=50, verbose_name='واحد')),
                ('storage_place', models.CharField(max_length=255, verbose_name='محل نگهداری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ماده اولیه',
                'verbose_name_plural': 'مواد اولیه',
            },
        ),
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام سایز')),
            ],
            options={
                'verbose_name': 'گزینه سایز',
                'verbose_name_plural': 'گزینه\u200cهای سایز',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام غذا')),
                ('dayOnWeek', models.CharField(blank=True, max_length=100, null=True, verbose_name='روز هفته')),
                ('time', models.DateField(blank=True, null=True, verbose_name='تاریخ')),
                ('ghazaye_asly', models.CharField(blank=True, max_length=300, null=True)),
                ('pish_ghaza', models.CharField(blank=True, max_length=300, null=True, verbose_name='پیش غذا')),
                ('deser', models.CharField(blank=True, max_length=300, null=True, verbose_name='دسر')),
                ('preparation_time_minutes', models.IntegerField(blank=True, null=True, verbose_name='زمان آماده\u200cسازی (دقیقه)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_finish', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='rest.category', verbose_name='دسته\u200cبندی')),
                ('available_sizes', models.ManyToManyField(to='rest.sizeoption', verbose_name='سایزهای موجود')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KitchenTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام وظیفه')),
                ('task_type', models.CharField(choices=[('preparation', 'آماده\u200cسازی'), ('cooking', 'پخت'), ('serving', 'سرو'), ('cleaning', 'نظافت'), ('other', 'سایر')], max_length=50, verbose_name='نوع وظیفه')),
                ('time', models.TimeField(verbose_name='زمان')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('servings_count', models.IntegerField(blank=True, null=True, verbose_name='تعداد سرو')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=50, verbose_name='وضعیت')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serving_tasks', to='rest.food', verbose_name='غذای مرتبط (در صورت وجود)')),
            ],
            options={
                'verbose_name': 'وظیفه آشپزخانه',
                'verbose_name_plural': 'وظایف آشپزخانه',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام ماده اولیه')),
                ('unit_of_measurement', models.CharField(choices=[('gram', 'گرم'), ('kg', 'کیلوگرم'), ('milliliter', 'میلی لیتر'), ('liter', 'لیتر'), ('piece', 'عدد')], max_length=50, verbose_name='واحد اندازه\u200cگیری')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی فعلی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_materials', to='rest.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'ماده اولیه',
                'verbose_name_plural': 'مواد اولیه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KitchenInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='موجودی')),
                ('location', models.CharField(max_length=100, verbose_name='محل نگهداری')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.rawmaterial', unique=True, verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'موجودی انبار آشپزخانه',
                'verbose_name_plural': 'موجودی انبار آشپزخانه',
                'ordering': ['raw_material__name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='موجودی')),
                ('min_quantity', models.FloatField(default=0, verbose_name='حداقل موجودی')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته\u200cبندی (کالا)')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.rawmaterial', unique=True, verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'موجودی انبار اصلی',
                'verbose_name_plural': 'موجودی انبار اصلی',
                'ordering': ['raw_material__name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('day_of_week', models.CharField(max_length=20, verbose_name='روز هفته')),
                ('appetizer', models.CharField(blank=True, max_length=255, null=True, verbose_name='پیش غذا')),
                ('dessert', models.CharField(blank=True, max_length=255, null=True, verbose_name='دسر')),
                ('main_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_dish_weekly_programs', to='rest.food', verbose_name='غذای اصلی')),
                ('second_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_dish_weekly_programs', to='rest.food', verbose_name='غذای دوم')),
            ],
            options={
                'verbose_name': 'برنامه هفتگی',
                'verbose_name_plural': 'برنامه\u200cهای هفتگی',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FoodRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار لازم')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.food', verbose_name='غذا')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.rawmaterial', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'ماده اولیه غذا',
                'verbose_name_plural': 'مواد اولیه غذا',
                'ordering': ['raw_material__name'],
                'unique_together': {('food', 'raw_material')},
            },
        ),
        migrations.CreateModel(
            name='FoodBOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='مقدار')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='rest.food', verbose_name='غذا')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.rawmaterial', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'ماده اولیه (BOM)',
                'verbose_name_plural': 'مواد اولیه (BOM)',
                'unique_together': {('food', 'raw_material')},
            },
        ),
    ]
