# Generated by Django 5.2.4 on 2025-07-26 13:41

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ'),
        ),
    ]
