# Generated by Django 5.2.4 on 2025-07-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_food_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='is_served',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام غذا')),
                ('preparation_time_minutes', models.IntegerField(blank=True, null=True, verbose_name='زمان آماده\u200cسازی (دقیقه)')),
                ('tedad', models.IntegerField(blank=True, null=True, verbose_name='تعداد سرو')),
                ('is_finish', models.BooleanField(default=False)),
            ],
        ),
    ]
