# Generated by Django 5.2.4 on 2025-07-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_is_served'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='is_served',
            new_name='servedfood',
        ),
    ]
