# Generated by Django 5.2.4 on 2025-07-26 21:11

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_rename_is_served_servedfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('count', models.IntegerField(default=1, verbose_name='تعداد')),
                ('issue_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('coupon_code', models.CharField(max_length=100, unique=True, verbose_name='کد ژتون')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='rest.food', verbose_name='غذا')),
            ],
            options={
                'verbose_name': 'ژتون',
                'verbose_name_plural': 'ژتون\u200cها',
                'ordering': ['-issue_date'],
            },
        ),
    ]
