# Generated by Django 5.2.4 on 2025-07-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_logintocupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='coding',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کدینگ'),
        ),
    ]
