# Generated by Django 5.2.4 on 2025-07-27 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_rawmaterial_coding'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(verbose_name='تاریخ برنامه')),
                ('meal_time', models.CharField(choices=[('breakfast', 'صبحانه'), ('lunch', 'ناهار'), ('dinner', 'شام'), ('snack', 'میان وعده')], max_length=50, verbose_name='وعده غذایی')),
                ('capacity_1', models.IntegerField(default=0, verbose_name='ظرفیت 1')),
                ('capacity_2', models.IntegerField(default=0, verbose_name='ظرفیت 2')),
                ('capacity_3', models.IntegerField(default=0, verbose_name='ظرفیت 3')),
                ('capacity_4', models.IntegerField(default=0, verbose_name='ظرفیت 4')),
                ('capacity_5', models.IntegerField(default=0, verbose_name='ظرفیت 5')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.food', verbose_name='غذا')),
            ],
            options={
                'verbose_name': 'برنامه هفتگی',
                'verbose_name_plural': 'برنامه هفتگی غذاها',
                'ordering': ['schedule_date', 'meal_time'],
                'unique_together': {('food', 'schedule_date', 'meal_time')},
            },
        ),
    ]
