# Generated by Django 5.2.4 on 2025-07-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_weeklyschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='capacity_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ظرفیت 1'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='capacity_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ظرفیت 2'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='capacity_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ظرفیت 3'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='capacity_4',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ظرفیت 4'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='capacity_5',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ظرفیت 5'),
        ),
    ]
