# Generated by Django 5.2.4 on 2025-07-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_alter_weeklyschedule_capacity_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='cooking_amount',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='مقدار طبخ'),
        ),
    ]
