# Generated by Django 5.2.4 on 2025-07-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_weeklyschedule_cooking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False, max_length=100, null=True, verbose_name='اتمام'),
        ),
    ]
