# Generated by Django 5.2.4 on 2025-07-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_alter_weeklyschedule_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rwmat',
            name='storage_place',
        ),
    ]
