# Generated by Django 5.2.4 on 2025-07-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_remove_rwmat_storage_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='capacity_1',
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='capacity_2',
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='capacity_3',
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='capacity_4',
        ),
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='capacity_5',
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='capacity_foroshi',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ظرفیت فروشی'),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='capacity_nazry',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ظرفیت حضرتی'),
        ),
    ]
