# Generated by Django 5.2.4 on 2025-07-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_alter_weeklyschedule_capacity_foroshi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='capacity_foroshi',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='ظرفیت فروشی'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='capacity_nazry',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='ظرفیت حضرتی'),
        ),
    ]
