# Generated by Django 5.2.4 on 2025-07-27 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_alter_weeklyschedule_capacity_foroshi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
    ]
