# Generated by Django 5.2.4 on 2025-07-27 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_remove_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='rest.category', verbose_name='دسته\u200cبندی'),
        ),
    ]
