# Generated by Django 5.2.4 on 2025-07-28 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0019_food_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='نام مشتری')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('transaction_type', models.CharField(choices=[('direct_sale', 'فروش مستقیم'), ('token_delivery', 'تحویل با ژتون')], max_length=20, verbose_name='نوع تراکنش')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان تراکنش')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.coupon', verbose_name='ژتون مرتبط')),
                ('food_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.food', verbose_name='غذا')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-timestamp'],
            },
        ),
    ]
