# Generated by Django 5.2.4 on 2025-07-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0020_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginToTahvil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
