# Generated by Django 5.2.4 on 2025-07-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0021_logintotahvil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logintotahvil',
            options={'verbose_name': 'کاربر پنل تحویل', 'verbose_name_plural': 'کاربران پنل تحویل'},
        ),
    ]
