# Generated by Django 5.2.4 on 2025-07-29 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0022_alter_logintotahvil_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='issued_nazry_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
