# Generated by Django 5.2.4 on 2025-07-29 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0023_weeklyschedule_issued_nazry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='issued_foroshi_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد فروشی صادر شده'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='issued_nazry_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد حضرتی صادر شده'),
        ),
    ]
