# Generated by Django 5.2.4 on 2025-08-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0024_weeklyschedule_issued_foroshi_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='current_stock',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='قیمت واحد به ریال', max_digits=15),
        ),
    ]
