# Generated by Django 5.2.4 on 2025-08-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0025_remove_rawmaterial_current_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='available_sizes',
        ),
        migrations.RemoveField(
            model_name='food',
            name='dayOnWeek',
        ),
        migrations.RemoveField(
            model_name='food',
            name='deser',
        ),
        migrations.RemoveField(
            model_name='food',
            name='ghazaye_asly',
        ),
        migrations.RemoveField(
            model_name='food',
            name='pish_ghaza',
        ),
        migrations.RemoveField(
            model_name='food',
            name='time',
        ),
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('main', 'غذای اصلی'), ('appetizer', 'پیش غذا'), ('dessert', 'دسر')], default='main', max_length=10, verbose_name='نوع غذا'),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='تمام شده است؟'),
        ),
    ]
