# Generated by Django 5.2.4 on 2025-08-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0026_remove_food_available_sizes_remove_food_dayonweek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='cooking_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='مقدار طبخ'),
        ),
    ]
