# Generated by Django 5.2.4 on 2025-08-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0027_alter_weeklyschedule_cooking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='cooking_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار طبخ'),
        ),
    ]
