# Generated by Django 5.2.4 on 2025-08-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0028_alter_weeklyschedule_cooking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='schedule_date',
            field=models.CharField(max_length=20, verbose_name='تاریخ برنامه (جلالی یا میلادی)'),
        ),
    ]
