# Generated by Django 5.2.4 on 2025-08-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0029_alter_weeklyschedule_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='schedule_date',
            field=models.DateField(verbose_name='تاریخ برنامه'),
        ),
    ]
