# Generated by Django 5.2.4 on 2025-08-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0030_alter_weeklyschedule_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی انبار اصلی'),
        ),
    ]
