# Generated by Django 5.2.4 on 2025-08-10 12:05

import django_jalali.db.models
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0031_rawmaterial_current_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(default='nazry', max_length=50, verbose_name='نوع ژتون'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='tracking_code',
            field=models.CharField(default=1, max_length=10, verbose_name='کد پیگیری گروهی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='family_name',
            field=models.CharField(default=1, max_length=200, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='issue_date',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today, verbose_name='تاریخ صدور'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='شماره تماس'),
        ),
    ]
